### PR TITLE
dirty fix for supporting new version of Joi validadator

### PR DESCRIPTION
**Pull request by Satyricon**
Fixing https://github.com/dialexa/relish/issues/15

### CODE REVIEW

**Comment by galenandrew** [comment]
Awesome @Satyricon!! Thank you for grabbing this one off the issues list! 🙌 

Do you have some time to include a test for this change?

**Comment by Marsup** [comment]
I think this needs a deeper change. Joi now correctly separates what's a key and what's a label, this part could be rewritten.

**Comment by galenandrew** [comment]
Thanks for the note @Marsup! We'll look into cleaning this up.

**Comment by Satyricon** [comment]
@galenandrew it is very hard to write a test as in old Joi version scenario with Array never happens. Would be much easier with if we update also Hapi and Joi versions.

**Comment by galenandrew** [comment]
@Satyricon thank you for your original PR here and apologies on such a delay getting a patch for this! After reviewing the various changes and versions to both Hapi and Joi, we decided to take a multi-release and version approach to this change instead of having relish support all versions of hapi/joi.

**Pull request closed without merging**
